name: ClassicalMaximals
version: "1.1"
license: "GPL-2.0-or-later"
date: 2026-05-26
description: |
    Maximal subgroups of classical groups

authors:
    - name: Maximilian Hauck
      url: mailto:mahauck@rhrk.uni-kl.de
    - name: Max Horn
      url: mailto:mhorn@rptu.de
    - name: Tristan Pfersdorff
      url: mailto:tristan.pfersdorff@edu.rptu.de
    - name: Christian Seeger
      url: mailto:christian.seeger@edu.rptu.de
    - name: Sergio Siccha
      url: mailto:siccha@mathematik.uni-kl.de

maintainers:
    - name: Max Horn
      url: mailto:mhorn@rptu.de
    - name: Christian Seeger
      url: mailto:christian.seeger@edu.rptu.de

GAP: ">= 4.15"

needed-pkgs:
    - name: "Forms"
      version: "1.2.12"
      url: "https://gap-packages.github.io/forms"
    - name: "recog"
      version: "1.5.0"
      url: "https://gap-packages.github.io/recog"

www: https://gap-packages.github.io/ClassicalMaximals/
readme: README.md
packageinfo: https://gap-packages.github.io/ClassicalMaximals/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/ClassicalMaximals/releases/download/v1.1/ClassicalMaximals-1.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HHPSS26</span>]   <b class='BibAuthor'>Hauck, M., Horn, M., Pfersdorff, T., Seeger, C. and Siccha, S.</b>,
     <i class='BibTitle'>ClassicalMaximals, Maximal subgroups of classical groups,
             Version 1.1</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/ClassicalMaximals/">https://gap-packages.github.io/ClassicalMaximals/</a></span>.
    </p>
    

bibtex: |
    @misc{ ClassicalMaximals,
      author =           {Hauck,  M. and Horn, M. and Pfersdorff, T. and Seeger,
                          C. and Siccha, S.},
      title =            {{ClassicalMaximals},  {Maximal  subgroups of classical
                          groups}, {V}ersion 1.1},
      month =            {May},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href
                          {https://gap-packages.github.io/ClassicalMaximals/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{ClassicalMaximals/}}},
      printedkey =       {HHPSS26}
    }

